version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install serverless -g
      - mvn clean compile
  build:
    commands:
      - mvn package -Pnative
  post_build:
    commands:
      - sls deploy

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
