version: 0.2

phases:
  install:
    commands:
      - mvn clean compile
  build:
    commands:
      - mvn package -Pnative

artifacts:
  files:
    - target/function.zip
    - js/basicAuthorizr.js
  name: jugda-registration
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
