version: '2.1'

services:
  localstack:
    image: localstack/localstack@sha256:fca191a03d4b421a9d1d1251eed27bd2b897490cfaa33eb80dd0118aae6d1529
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,s3,ses
    volumes:
      - ./src/test/resources/dynamodb-schema.json:/tmp/dynamodb-schema.json
      - ./src/test/resources/s3/eventData.json:/tmp/eventData.json
      - ./target/events.json:/tmp/events.json
      - ./configure_localstack.sh:/docker-entrypoint-initaws.d/setup.sh
