service: ${self:custom.tenant}-registration

provider:
  name: aws
  runtime: provided
  stage: prod
  region: eu-central-1
  endpointType: REGIONAL
  apiGateway:
    shouldStartNameWithService: true
  memorySize: 512
  timeout: 30
  deploymentBucket:
    name: dasniko.serverless.deployments.${self:provider.region}
  logRetentionInDays: 30
  environment:
    DISABLE_SIGNAL_HANDLERS: 'true'
    APP_DYNAMODB_TABLE: ${self:service}
    APP_EVENTS_DATA_BUCKET: ${self:custom.tenant}
    APP_TENANT_ID: ${self:custom.tenant}
    QUARKUS_PROFILE: ${self:custom.tenant}
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.APP_DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.APP_DYNAMODB_TABLE}/index/*"
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: "arn:aws:s3:::${self:custom.tenant}/*"
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendTemplatedEmail
            - ses:SendBulkTemplatedEmail
          Resource: ${self:custom.secrets.${self:custom.tenant}Registration.aws.sesIdentity}
        - Effect: Allow
          Action:
            - ses:SendTemplatedEmail
            - ses:SendBulkTemplatedEmail
          Resource: ${self:custom.secrets.${self:custom.tenant}Registration.aws.sesTemplate}
        - Effect: Allow
          Action:
            - ses:CreateTemplate
            - ses:UpdateTemplate
          Resource: "*"

custom:
  tenant: ${env:TENANT, 'jugda'}
  secrets: ${ssm:/aws/reference/secretsmanager/jugda-secrets}

package:
  individually: true

functions:
  admin:
    handler: not.used.in.provided.runtime
    events:
      - http:
          path: /admin/{proxy+}
          method: any
          authorizer:
            name: basicAuthorizer
            type: token
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 300
    package:
      artifact: target/function.zip
  public:
    handler: not.used.in.provided.runtime
    environment:
      SLACK_OAUTH_ACCESS_TOKEN: ${self:custom.secrets.${self:custom.tenant}Registration.slack.access_token}
      SLACK_CHANNEL_GENERAL: ${self:custom.secrets.${self:custom.tenant}Registration.slack.channel_general}
    events:
      - http:
          path: /{proxy+}
          method: any
    package:
      artifact: target/function.zip
  basicAuthorizer:
    handler: src/main/js/basicAuthorizr.handler
    runtime: nodejs16.x
    memorySize: 128
    timeout: 3
    environment:
      REGISTRATION_ADMIN: ${self:custom.secrets.${self:custom.tenant}Registration.registration.admin}
      REGISTRATION_SECRET: ${self:custom.secrets.${self:custom.tenant}Registration.registration.secret}
    package:
      include:
        - src/main/js/basicAuthorizr.js
      exclude:
        - "*.*"
        - "*/**"

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: eventId
            AttributeType: S
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 2
        TableName: ${self:provider.environment.APP_DYNAMODB_TABLE}
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        SSESpecification:
          SSEEnabled: true
        GlobalSecondaryIndexes:
          -
            IndexName: event-email-index
            KeySchema:
              -
                AttributeName: eventId
                KeyType: HASH
              -
                AttributeName: email
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 2
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: 401
